-- autogenerated by reconstant - do not edit!
package constants is

	-- constants
	constant SOME_CONSTANT : string := "this is a constant string";
	constant OTHER_CONSTANT : integer := 42;

	-- enums
	type SomeEnum is
		A,
		B,
		C
	end type;
	type OtherEnum is
		FOO,
		BAR
	end type;

end package;